### ISSUE TITLE
Issue with docking compass on webview

### ISSUE THREAD

**Issue by kerriganb** [npolyak/NP.Avalonia.Demos#1]
Hi Nick, firstly - awesome docking framework ... Love it!!! Soooo much better than AvaloniaDock :)

I did notice something though ... If you put a webview control (CefGlue) as a DockItem ... and then try to drag another document on top of it ...the compass does not show or is partly hidden ...My guess is that you do not use an adorner for the compass and the webview is occluding it ...

Do you think you can have a look? Or if you point me in the right direction I can create a PR for you...

Here is a screen shot of what I'm talking about...I would expect to see a compass here (above the webview control) ... note also the cut off edge compass...

thanks again for awesome work...
Kerrigan.

![dock](https://user-images.githubusercontent.com/5913794/147294621-a63f5b1f-4b9f-4f84-a5d2-55947f02f2f1.png)

**Comment by npolyak** [comment]
Hey Kerrigan,

Thank you for your good words about the UniDock! It is very nice to feel appreciated :)

Please, star the UniDock repository and if you have any friends who use it and like it, ask them to star it also. 

yes, this is probably the issue. It is best for the compass to be not even an adorner but a separate semi-transparent window so that it will not be blocked even by the dragged panel. I'll be having several days off before the new year so perhaps I'll try to work on it. 

Regards,

Nick

**Comment by kerriganb** [comment]
Ah, sweet! What a nice xmas present :) ...Definitely starred it and will let others know ....have a good one...

**Comment by npolyak** [comment]
I think I fixed it. Please, try the latest version of UniDock.

**Comment by kerriganb** [comment]
Hi Nick, i can confirm this now works with web browser controls. Thank you very much (especially for quick turnaround)!! Awesome stuff...

**Comment by npolyak** [comment]
Great pleasure!
